
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_project_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: sample_project_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: sample_project_production
  pool: 5
  username: postgres
  password: postgres
